name: MinealotHungerGames
version: ${project.version}.${BUILD_NUMBER}
main: org.Th3Hermit.hungergames.HungerGames
authors: [Th3Hermit, Keepsedge, Double0negative]
description: Fully Automated Hunger Games Plugin!

commands:
    hungergames:
        description: Hunger Games Command
        usage: /hg <command> <args>
        aliases: [hungergames, hg, sg]

