name: MinealotHungerGames
version: ${project.version}.${BUILD_NUMBER}
main: org.Th3Hermit.hungergames.HungerGames
authors: [Double0negative, Th3Hermit]
description: Fully Automated Hunger Games Plugin!

commands:
    hungergames:
        description: Hunger Games Command
        usage: /hg <command> <args>
        aliases: [hg, hungergames, sg]

